version: "1.0.0"
services:
 babone_docker:
   image: node:16-alpine
   command: sh -c "npm install && npm run dev"
   container_name: babone_docker
  #  entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
      - ./:/srv/app
      # - type: bind
      #   source: ./
      #   target: /srv/app
   tty: true     
   environment:
    VITE_SUPA_URL: https://blbjfpyjxzhppkmopebe.supabase.co
    VITE_SUPA_API_PUBLIC_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsYmpmcHlqeHpocHBrbW9wZWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODU5ODgyMjUsImV4cCI6MjAwMTU2NDIyNX0.HkrKI0YtX0Nc5FuBr8692bDGJFq5G1GX7VKs0ekBAwg
    VITE_SUPA_API_PRIVATE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsYmpmcHlqeHpocHBrbW9wZWJlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NTk4ODIyNSwiZXhwIjoyMDAxNTY0MjI1fQ.O_yRFoIhZpVUMwL0h3-YemXubS124l56aE2maoUg8qw
    
   